export const stats = [
    'agility',
    'constitution',
    'empathy',
    'intuition',
    'memory',
    'presence',
    'quickness',
    'reasoning',
    'self Discipline',
    'strength'
];

export const races = [
    "Avinarc",
    "Dwarf",
    "Elf, fair",
    "Elf, grey",
    "Elf, high",
    "Elf, wood",
    "Gnoll",
    "Gnome",
    "Goblin",
    "Gratar",
    "Half-Elf",
    "Halfling",
    "Hobgoblin",
    "Human, cave",
    "Human, common",
    "Human, high",
    "Human, mixed",
    "Hvasstonn",
    "Idiyva",
    "Kobold",
    "Nycamerith",
    "Orc, greater",
    "Orc, grey",
    "Orc, lesser",
    "Orc, scrug",
    "Orc, vard",
    "Plynos",
    "Sea-kral",
    "Sibbicai",
    "Sohleugir",
    "Sstoi'isslythi",
    "Troll",
    "Vulfen"
];

export const cultures = [
    "Cosmopolitan",
    "Harsh",
    "Highland",
    "Mariner",
    "Nomad",
    "Reaver",
    "Rural",
    "Sylvan",
    "Underground",
    "Urban"
];

export const professions = [
    "No Profession",
    "Fighter",
    "Warrior Monk",
    "Thief",
    "Rogue",
    "Laborer",
    "Scholar",
    "Cleric",
    "Druid",
    "Magician",
    "Illusionist",
    "Mentalist",
    "Lay Healer",
    "Healer",
    "Mystic",
    "Sorcerer",
    "Ranger",
    "Paladin",
    "Monk",
    "Magent",
    "Bard",
    "Dabbler"
];

export const realms = [
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Channeling",
    "Channeling",
    "Essence",
    "Essence",
    "Mentalism",
    "Mentalism",
    "Channeling/Mentalism",
    "Essence/Mentalism",
    "Channeling/Essence",
    "Channeling",
    "Channeling",
    "Mentalism",
    "Mentalism",
    "Essence",
    "Essence",
];